services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ImaginAi
      POSTGRES_PASSWORD: ImaginAipass
      POSTGRES_DB: ImaginAidb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ImaginAi -d ImaginAidb"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    environment:
      DB_HOST: postgres
      DB_USER: ImaginAi
      DB_PASSWORD: ImaginAipass
      DB_NAME: ImaginAidb
    ports:
      - "5050:5050"
    depends_on:
      postgres:
        condition: service_healthy

  chat-bot:
    build: ./chat-bot
    environment:
      DB_HOST: postgres
      DB_USER: ImaginAi
      DB_PASSWORD: ImaginAipass
      DB_NAME: ImaginAidb
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:

networks:
  default:
    driver: bridge